config/routes.rb
Rails.application.routes.draw do
  root 'sushi_rolls#index'
  resources :sushi_rolls
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sushi_roll.rb
class SushiRoll < ApplicationRecord
  validates_presence_of :name, :price
   validates_numericality_of :price
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/sushi_rolls_controller.rb
class SushiRollsController < ApplicationController
  before_action :set_sushi_roll, only: [:show, :edit, :update, :destroy]

  # GET /sushi_rolls
  def index
    @sushi_rolls = SushiRoll.all
  end

  # GET /sushi_rolls/1
  def show
  end

  # GET /sushi_rolls/new
  def new
    @sushi_roll = SushiRoll.new
  end

  # GET /sushi_rolls/1/edit
  def edit
  end

  # POST /sushi_rolls
  def create
    @sushi_roll = SushiRoll.new(sushi_roll_params)

    if @sushi_roll.save
      redirect_to @sushi_roll, notice: 'Sushi roll was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /sushi_rolls/1
  def update
    if @sushi_roll.update(sushi_roll_params)
      redirect_to @sushi_roll, notice: 'Sushi roll was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /sushi_rolls/1
  def destroy
    @sushi_roll.destroy
    redirect_to sushi_rolls_url, notice: 'Sushi roll was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sushi_roll
      @sushi_roll = SushiRoll.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def sushi_roll_params
      params.require(:sushi_roll).permit(:name, :price, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sushi_rolls_helper.rb
module SushiRollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SushiTesting</title>
    
       <p class="alert"><%= alert %></p>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sushi_rolls/_form.html.erb
<%= form_with(model: sushi_roll, local: true) do |form| %>
  <% if sushi_roll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sushi_roll.errors.count, "error") %> prohibited this sushi_roll from being saved:</h2>

      <ul>
      <% sushi_roll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :sushi_roll_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :sushi_roll_price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :sushi_roll_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sushi_rolls/edit.html.erb
<h1>Editing Sushi Roll</h1>

<%= render 'form', sushi_roll: @sushi_roll %>

<%= link_to 'Show', @sushi_roll %> |
<%= link_to 'Back', sushi_rolls_path %>

app/views/sushi_rolls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sushi Rolls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sushi_rolls.each do |sushi_roll| %>
      <tr>
        <td><%= sushi_roll.name %></td>
        <td><%= sushi_roll.price %></td>
        <td><%= sushi_roll.description %></td>
        <td><%= link_to 'Show', sushi_roll %></td>
        <td><%= link_to 'Edit', edit_sushi_roll_path(sushi_roll) %></td>
        <td><%= link_to 'Destroy', sushi_roll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


 <%= button_to 'New Sushi Roll', new_sushi_roll_path, method: :get %>

app/views/sushi_rolls/new.html.erb
<h1>New Sushi Roll</h1>

<%= render 'form', sushi_roll: @sushi_roll %>

<%= link_to 'Back', sushi_rolls_path %>

app/views/sushi_rolls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sushi_roll.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @sushi_roll.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sushi_roll.description %>
</p>

<%= link_to 'Edit', edit_sushi_roll_path(@sushi_roll) %> |
<%= link_to 'Back', sushi_rolls_path %>